name: Java CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Rename JAR to app.jar
        run: mv target/*.jar target/app.jar

  deploy_dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to DEV (Simulated)
        run: echo "Deployed to DEV"

  deploy_test:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' }}
    needs: deploy_dev
    steps:
      - name: Deploy to TEST (Simulated)
        run: echo "Deployed to TEST"

  deploy_stg:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    environment: staging
    steps:
      - name: Simulated Deployment to STAGING via SCP/SSH
        run: |
          echo "scp -i mock-key.pem target/app.jar ec2-user@1.2.3.4:/home/ec2-user/"
          echo "ssh -i mock-key.pem ec2-user@1.2.3.4 'pkill -f java -jar'"
          echo "ssh -i mock-key.pem ec2-user@1.2.3.4 'mv /home/ec2-user/app.jar /home/ec2-user/app-latest.jar'"
          echo "ssh -i mock-key.pem ec2-user@1.2.3.4 'nohup java -jar /home/ec2-user/app-latest.jar &'"
